<?php

$testImport = 'foo';

$fakeData = 

[
    [
        'title' => 'GE Ductless Cold Climate Training', 
        'trainingLogo' => 'true',
        'Date_1'=> 'Wednesday, May 15 2024',
        'Date_2' => '08:00 AM to 01:00 PM',
        'Company' => 'F.W. Webb Company',
        'Address_1' => '700 Broadway',
        'Address_2' => 'Malden, Massachusetts 02148',
        'Post_Address_Comment' => '',
        'Topics_Title'=> 'Topics covered will include:',
        'Topics_contents'=> ['• Introduction to GE Ductless','• Technology and Product Lineup','• Installation and Startup','• System Operation and Control','• Troubleshooting','• Application'],
        //'Topics'   => ['Introduction to GE Ductless','Technology and Product Lineup','Installation and Startup','System Operation and Control','Troubleshooting','Application'],
        'Italics_msg' => 'Lunch and refreshments will be provided',
        'Bold_last_msg' => 'Space is limited...register today!',
        'Last_msg_content' => 'Click Here to Register',
        'Last_msg_link' => 'https://form.jotform.com/241015259928156'
    ],
    [
        'title' => 'Understanding & How to Troubleshoot Air Flow Class', 
        'trainingLogo' => 'true',
        'Date_1'=> 'Thursday, May 16 2024',
        'Date_2' => '08:00 AM to 10:00 AM',
        'Company' => 'F.W. Webb Company',
        'Address_1' => '261 Route 46 West',
        'Address_2' => 'Elmwood Park, New Jersey 07407',
        'Post_Address_Comment' => ["Join F.W. Webb's in-house HVAC/R tech for this informative class on understanding and troubleshooting air flow."],
        // 'Topics'   => ['Introduction to GE Ductless','Technology and Product Lineup','Installation and Startup','System Operation and Control','Troubleshooting','Application'],
        'Topics_Title' => 'Key topics include:',
        'Topics_contents' => ['• How to take & understand static pressures','• Proper procedure for taking static pressure','• Diagnosing issues using airflow readings','• Understanding what problems arise with improper airflow'],
        'Italics_msg' => 'Bagels and coffee will be provided',
        'Bold_last_msg' => 'Space is limited...register today!',
        'Last_msg_content' => 'Click Here to Register',
        'Last_msg_link' => 'https://form.jotform.com/241073360477152'
    ],
        [
        'title' => 'Lunch & Learn with Ideal Heating', 
        'trainingLogo' => 'true',
        'Date_1'=> 'Thursday, May 16 2024',
        'Date_2' => '11:30 AM to 01:30 PM',
        'Company' => 'F.W. Webb Company',
        'Address_1' => '30 Pomeroy Ave.',
        'Address_2' => 'Meriden, Connecticut 06450',
        'Post_Address_Comment' => ["Join us for an upcoming Lunch & Learn at F.W. Webb in Meriden, CT to see the latest and greatest from Ideal Heating NA."],
        // 'Topics'   => ['Introduction to GE Ductless','Technology and Product Lineup','Installation and Startup','System Operation and Control','Troubleshooting','Application'],
        'Topics_Title'   => '',
        'Topics_contents'   => '',
        'Italics_msg' => '',
        'Bold_last_msg' => '',
        'Last_msg_content' => '',
        'Last_msg_link' => ''
        ],
        [
        'title' => 'NAVAC Best Practices for Refrigerant Evacuation and Recovery', 
        'trainingLogo' => 'true',
        'Date_1'=> 'Thursday, May 16 2024',
        'Date_2' => '04:00 PM to 08:00 PM',
        'Company' => 'BADSONS Beer Co.',
        'Address_1' => '251 Roosevelt Drive',
        'Address_2' => 'Derby, Connecticut 06418',
        'Post_Address_Comment' => ["Join F.W. Webb's in-house HVAC/R tech for this informative class on understanding and troubleshooting air flow."],
        // 'Topics'   => ['Introduction to GE Ductless','Technology and Product Lineup','Installation and Startup','System Operation and Control','Troubleshooting','Application'],
        'Topics_Title' => 'Topics to be covered include:',
        'Topics_contents' => ['','<b>Evacuation Explained</b>','Do you have a pump or a paperweight? Make sure your tools are working for you, and develop a firm grasp on the best practices for the evacuation of HVAC/R equipment','','<b>Recovery Demystified</b>','Have your cake and eat it too - achieve true and complete recovery of ALL liquid and vapor faster and more efficient than ever before.'],
        'Italics_msg' => 'Food and drinks will be provided',
        'Bold_last_msg' => 'Space is limited...register today!',
        'Last_msg_content' => 'Click Here to Register',
        'Last_msg_link' => 'https://form.jotform.com/241153449759162'
        ],
        [
        'title' => 'Counter Day Breakfast with White-Rodgers', 
        'trainingLogo' => 'false',
        'Date_1'=> 'Monday, May 20 2024',
        'Date_2' => '08:00 AM to 10:00 AM',
        'Company' => 'F.W. Webb Company',
        'Address_1' => '33 New London Turnpike',
        'Address_2' => 'Norwich, Connecticut 06360',
        'Post_Address_Comment' => ["Join us for breakfast with RSY Associates, featuring White-Rodgers universal furnace controls and hot surface ignitors.","Learn more about the White-Rodgers App for cross referencing OEM furnace controls/gas valves to White-Rodgers replacement models."],
        // 'Topics'   => ['Introduction to GE Ductless','Technology and Product Lineup','Installation and Startup','System Operation and Control','Troubleshooting','Application'],
        'Topics_Title'   => '',
        'Topics_contents'   => '',
        'Italics_msg' => '',
        'Bold_last_msg' => '',
        'Last_msg_content' => '',
        'Last_msg_link' => ''
        ],
        [
        'title' => 'Counter Day Breakfast with URELL', 
        'trainingLogo' => 'false',
        'Date_1'=> 'Tuesday, May 21 2024',
        'Date_2' => '11:00 AM to 01:00 PM',
        'Company' => 'F.W. Webb Company',
        'Address_1' => '33 New London Turnpike',
        'Address_2' => 'Norwich, Connecticut 06360',
        'Post_Address_Comment' => ["Join us for lunch with URELL who will be showcasing products from American Standard, Zoeller and Uponor."],
        // 'Topics'   => ['Introduction to GE Ductless','Technology and Product Lineup','Installation and Startup','System Operation and Control','Troubleshooting','Application'],
        'Topics_Title'   => '',
        'Topics_contents'   => '',
        'Italics_msg' => '',
        'Bold_last_msg' => '',
        'Last_msg_content' => '',
        'Last_msg_link' => ''
        ],
        [
        'title' => 'Counter Day Breakfast', 
        'trainingLogo' => 'false',
        'Date_1'=> 'Tuesday, May 21 2024',
        'Date_2' => '07:00 AM to 11:00 AM',
        'Company' => 'F.W. Webb Company',
        'Address_1' => '34 Lamar St.',
        'Address_2' => 'West Babylon, New York 11704',
        'Post_Address_Comment' => ["Join us for breakfast with Venco Sales featuring products from Rheem, U.S. Boiler, Resideo, Grundfos and Testo."],
        // 'Topics'   => ['Introduction to GE Ductless','Technology and Product Lineup','Installation and Startup','System Operation and Control','Troubleshooting','Application'],
        'Topics_Title'   => '',
        'Topics_contents'   => '',
        'Italics_msg' => '',
        'Bold_last_msg' => '',
        'Last_msg_content' => '',
        'Last_msg_link' => ''
        ],
        [
        'title' => 'Rheem Heat Pump Water Heater Training', 
        'trainingLogo' => 'true',
        'Date_1'=> 'Thursday, May 23 2024',
        'Date_2' => '08:00 AM to 10:30 AM',
        'Company' => 'F.W. Webb Company',
        'Address_1' => '180 Olde Canal Drive',
        'Address_2' => 'Lowell, Massachusetts 01851',
        'Post_Address_Comment' => ["Join us for breakfast and a morning of Rheem product training with a focus on heat pump options."],
        // 'Topics'   => ['Introduction to GE Ductless','Technology and Product Lineup','Installation and Startup','System Operation and Control','Troubleshooting','Application'],
        'Topics_Title' => 'Topics to be covered include:',
        'Topics_contents' => ['• Pro Terra models','• Benefits of heat pumps','• Troubleshooting','• Energy Savings','• System Monitoring'],
        'Italics_msg' => '',
        'Bold_last_msg' => 'Space is limited...register today!',
        'Last_msg_content' => 'Please email thar@fwwebb.com to secure your spot now for this exclusive training event.',
        'Last_msg_link' => ''
        ],
        [
        'title' => 'Samsung Heat Pump Training', 
        'trainingLogo' => 'true',
        'Date_1'=> 'Thursday, May 23 2024',
        'Date_2' => '08:30 AM to 03:30 PM',
        'Company' => 'F.W. Webb Company',
        'Address_1' => '50 Everberg Road',
        'Address_2' => 'Woburn, Massachusetts 01801',
        'Post_Address_Comment' => ["This course reviews the proper operation of Samsung single zone and multi zone heat pump systems. The course also covers troubleshooting error codes and accurate diagnosis of each system. Indoor and outdoor unit disassembly procedures are reviewed.","","<b>This class is required to qualify for the Mass Save Cold Climate Rebate Program.</b>"],
        // 'Topics'   => ['Introduction to GE Ductless','Technology and Product Lineup','Installation and Startup','System Operation and Control','Troubleshooting','Application'],
        'Topics_Title'   => '',
        'Topics_contents'   => '',
        'Italics_msg' => 'Breakfast refreshments and lunch will be provided.',
        'Bold_last_msg' => 'Space is limited...register today!',
        'Last_msg_content' => 'Click Here to Register',
        'Last_msg_link' => 'https://form.jotform.com/241264910990155'
        ],
        [
        'title' => 'VIQUA Water Filtration Training', 
        'trainingLogo' => 'true',
        'Date_1'=> 'Thursday, May 23 2024',
        'Date_2' => '11:00 AM to 02:00 PM',
        'Company' => 'F.W. Webb Company',
        'Address_1' => '20 Webb Drive',
        'Address_2' => 'Hampden, Maine 04444',
        'Post_Address_Comment' => ["Join F.W. Webb and VIQUA for this water treatment solutions training featuring VIQUA UV water treatment systems covering numerous sizes, flow rates and applications."],
        // 'Topics'   => ['Introduction to GE Ductless','Technology and Product Lineup','Installation and Startup','System Operation and Control','Troubleshooting','Application'],
        'Topics_Title'   => '',
        'Topics_contents'   => '',
        'Italics_msg' => 'Lunch will be provided',
        'Bold_last_msg' => 'Space is limited...register today!',
        'Last_msg_content' => 'Click Here to Register',
        'Last_msg_link' => 'https://form.jotform.com/241275647712156'
        ],
        [
        'title' => 'Counter Day Breakfast with SLOAN', 
        'trainingLogo' => 'false',
        'Date_1'=> 'Thursday, May 23 2024',
        'Date_2' => '12:00 PM to 02:00 PM',
        'Company' => 'F.W. Webb Company',
        'Address_1' => '420 Winchester Street',
        'Address_2' => 'Keene, New Hampshire 03431',
        'Post_Address_Comment' => ["Join us for lunch from the Voodoo Box food truck and check out the Sloan mobile walk-in showroom!"],
        // 'Topics'   => ['Introduction to GE Ductless','Technology and Product Lineup','Installation and Startup','System Operation and Control','Troubleshooting','Application'],
        'Topics_Title'   => '',
        'Topics_contents'   => '',
        'Italics_msg' => '',
        'Bold_last_msg' => '',
        'Last_msg_content' => '',
        'Last_msg_link' => ''
        ],
        [
        'title' => 'Samsung HVAC Training', 
        'trainingLogo' => 'true',
        'Date_1'=> 'Friday, May 24 2024',
        'Date_2' => '10:00 AM to 12:00 PM',
        'Company' => 'F.W. Webb Company',
        'Address_1' => '452 Tom Miller Rd.',
        'Address_2' => 'Plattsburgh, New York 12901',
        'Post_Address_Comment' => ["Join F.W. Webb and Paul Blanchard for a day of Samsung product training."],
        // 'Topics'   => ['Introduction to GE Ductless','Technology and Product Lineup','Installation and Startup','System Operation and Control','Troubleshooting','Application'],
        'Topics_Title'   => '',
        'Topics_contents'   => '',
        'Italics_msg' => '',
        'Bold_last_msg' => 'Space is limited...register today!',
        'Last_msg_content' => 'To register please email britt@fwwebb.com.',
        'Last_msg_link' => ''
        ],
        [
        'title' => 'Bosch IDS Heat Pump Training', 
        'trainingLogo' => 'true',
        'Date_1'=> 'Tuesday, May 28 2024',
        'Date_2' => '08:00 AM to 12:00 PM',
        'Company' => 'F.W. Webb Company',
        'Address_1' => '101 Hampden Street',
        'Address_2' => 'Boston, Massachusetts 02119',
        'Post_Address_Comment' => ["Join F.W. Webb and Paul Blanchard for a day of Samsung product training."],
        // 'Topics'   => ['Introduction to GE Ductless','Technology and Product Lineup','Installation and Startup','System Operation and Control','Troubleshooting','Application'],
        'Topics_Title' => 'Topics covered will include:','contents',        
        'Topics_contents' => ['• Variable capacity air source heat pump (VCHP operations)','• Load Calculations and why they matter','• Sizing and selection methods','• System design options and considerations','• Control strategies and thermostat options'],        
        'Italics_msg' => 'Lunch will be provided',
        'Bold_last_msg' => 'Space is limited...register today!',
        'Last_msg_content' => 'Click Here to Register',
        'Last_msg_link' => 'https://form.jotform.com/241283906412150']
]

?>

